#arrayStack: arrayStack.o
#arrayStack.o: arrayStack.c

CC = gcc
COMPILE = ../out/intermediate

#all: $(COMPILE)/arrayStack.o

test2:
	@echo "included test2 routine"

#%.o: %.c
#	$(CC) -c $< -o $(COMPILE)/$@
